
jobs:
- job: windows
  displayName: Windows
  pool:
    vmImage: 'vs2015-win2012r2'
  strategy:
    matrix:
      x86:
        target_type: x86
        vc_version: 2015
      x64:
        target_type: x64
        vc_version: 2015
      x64_pe:
        target_type: x64_pe
        vc_version: 2015
  steps:
  - script: git config --global core.autoCRLF false
    displayName: "Disable git autoCRLF"
  - checkout: self
    displayName: "checkout"
    fetchDepth: 50
  - script: cmd /c PCbuild\my_build.bat $(target_type) $(vc_version)
    displayName: Build
  - script: cmd /c PCbuild\my_test.bat $(target_type) $(vc_version)
    displayName: Test
